### ISSUE TITLE
flycheck fringe bitmaps

### ISSUE THREAD

**Issue by valignatev** [nashamri/spacemacs-theme#119] opened 2018-07-02 15:12 UTC
Hi! Currently, fringe error/warning bitmaps are not "round", and look like chevrons instead:
![image](https://user-images.githubusercontent.com/7038954/42171829-ae7dca8e-7e5d-11e8-83f6-f3aac3e20b8e.png)

I've checked the code, and it seems that spacemacs-theme only defines colors. It means that Spacemacs overrides the bitmap somewhere else, not in the theme. I think that putting it in the theme is a logical thing, because fringe bitmap is a visual thing, and it's in the screenshots in the readme :)
What do you think?

**Comment by valignatev** [comment] 2018-07-02 15:15
Related spacemacs code for the reference: https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/layers/%2Bcheckers/syntax-checking/packages.el#L38

**Comment by nashamri** [comment] 2018-07-02 18:38
@valignatev hmm, I'm not sure what's going on here. On my setup it looks as in the screenshots (rounded). I've attached a little screenshot of it:
![image](https://user-images.githubusercontent.com/1207107/42180447-9c7e3f74-7e37-11e8-9834-93d7bf901b82.png)
Do you see this on the `develop` branch?

**Comment by valignatev** [comment] 2018-07-03 03:02
Thanks for the fast response! I'm not using Spacemacs, I'm just using this theme with my custom emacs config. And this repo doesn't seem to have a develop branch

**Comment by nashamri** [comment] 2018-07-05 16:32
@valignatev Yeah I see, I thought you were using spacemacs, thus the mentioned `develop` branch :smile:. I'm not sure about this, because if I had this custom fringe indicator in the theme's code, this will be a duplicate of what's already there in spacemacs. Maybe as a middle ground, we can just take that code and put it in the README file of this theme for the users to add it themselves in their configs.

**Comment by valignatev** [comment] 2018-07-05 17:30
Yeah, I actually think this is a great way to both avoid duplication and to educate people about Emacs UI capabilities a little bit.

**Comment by nashamri** [comment] 2018-07-05 19:03
Awesome, I'll do that once I come back from my holidays. Until then, please let this issue open :smile: :tropical_drink:

**Comment by nashamri** [comment] 2018-08-17 15:41
This should solve this issue:
ec1283ff8fa10a575e599b7b160e6082f1109409

**Closed** 2018-08-17 15:54 UTC
